# Log into ArcGIS Online

In [1]:
from arcgis.gis import GIS
import os
import pandas as pd
import  json

In [2]:
gis = GIS("http://slustl.maps.arcgis.com/home", "gregbrunner_slugis")

Enter password: ········

# Create a Dictionary of Months

In [3]:
month_dict = {'01':'January',
              '02':'February',
              '03':'March',
              '04':'April',
              '05':'May',
              '06':'June',
              '07':'July',
              '08':'August',
              '09':'September',
              '10':'October',
              '11':'November',
              '12':'December'
}

# Create a Map

In [4]:
world_map = gis.map()
world_map.basemap = 'dark-gray'
world_map

MapView(basemaps=['dark-gray', 'dark-gray-vector', 'gray', 'gray-vector', 'hybrid', 'national-geographic', 'oc…

# For every month in 2017

## 1. Read data into a dataframe

## 2. Convert the DataFrame to a CSV

## 3. Publish the CSV

## 4. Add the Published Layer to a Map and Render on the *Value* field

## 5. Track the month fields so we can do Mann-Kendall on the data later

In [5]:
val_list = []

c = 'GRC'

for m in month_dict.keys():
    print(c)
    
    url = 'http://popdata.unhcr.org/api/stats/asylum_seekers_monthly.json?year=2017&month=' + m + '&coa=' + c

    print('looking at ' + m)
    
    df = pd.read_json(url)
    
    csv = c + '_' + month_dict[m] + '.csv'
    df.to_csv(csv)
    
    print('Month is ' + str(csv[4:]))
    val_list.append('value'+ str(csv[4:]))
    
    print('Publishing ' + csv)
    
    csv_content = gis.content.add({}, csv)
    layers = csv_content.publish(None, {"Address":"country_of_origin_en"})
    world_map.add_layer(layers, {"renderer":"ClassedSizeRenderer", "field_name":"value"})
    print('Done ' + csv)

GRC
looking at 01
Month is January.csv
Publishing GRC_January.csv
Done GRC_January.csv
GRC
looking at 02
Month is February.csv
Publishing GRC_February.csv
Done GRC_February.csv
GRC
looking at 03
Month is March.csv
Publishing GRC_March.csv
Done GRC_March.csv
GRC
looking at 04
Month is April.csv
Publishing GRC_April.csv
Done GRC_April.csv
GRC
looking at 05
Month is May.csv
Publishing GRC_May.csv
Done GRC_May.csv
GRC
looking at 06
Month is June.csv
Publishing GRC_June.csv
Done GRC_June.csv
GRC
looking at 07
Month is July.csv
Publishing GRC_July.csv
Done GRC_July.csv
GRC
looking at 08
Month is August.csv
Publishing GRC_August.csv
Done GRC_August.csv
GRC
looking at 09
Month is September.csv
Publishing GRC_September.csv
Done GRC_September.csv
GRC
looking at 10
Month is October.csv
Publishing GRC_October.csv
Done GRC_October.csv
GRC
looking at 11
Month is November.csv
Publishing GRC_November.csv
Done GRC_November.csv
GRC
looking at 12
Month is December.csv
Publishing GRC_December.csv
Done GRC_December.csv

In [9]:
val_list

['valueJanuary.csv',
 'valueFebruary.csv',
 'valueMarch.csv',
 'valueApril.csv',
 'valueMay.csv',
 'valueJune.csv',
 'valueJuly.csv',
 'valueAugust.csv',
 'valueSeptember.csv',
 'valueOctober.csv',
 'valueNovember.csv',
 'valueDecember.csv']

# Save Webmap

In [6]:
webmap_properties = {'title':'UNHCR Project - Greg B 10281018',
                     'snippet':'UNHCR Webmap',
                     'tags':['UNHCR']}
world_map.save(webmap_properties)
print("Done")

Done

# Applying the Mann-Kendall

## For each excel spreadsheet...

### 1. Read it inot a DataFrame

### 2. Rename columns to specify the month

### 3. Merge (read *join*) the DataFrame to all previously read DataFrames

In [7]:
csv_files = []
for file in os.listdir():
    if 'GRC'  in file:
        csv_files.append(file)
print(csv_files)

['GRC_April.csv', 'GRC_August.csv', 'GRC_December.csv', 'GRC_February.csv', 'GRC_January.csv', 'GRC_July.csv', 'GRC_June.csv', 'GRC_March.csv', 'GRC_May.csv', 'GRC_November.csv', 'GRC_October.csv', 'GRC_September.csv']

In [8]:
init_df = pd.read_csv(csv_files[0]).loc[:,'country_of_origin_en']
#val_list = []

for cf in csv_files:
    print('Month is ' + str(cf[4:]))
    #val_list.append('value'+ str(cf[4:]))

    df = pd.read_csv(cf)
    new_df = df.loc[:, 'country_of_origin_en':'value']
    new_df.rename(columns=lambda x: x+str(cf[4:]), inplace=True)
    try:
        init_df = pd.merge(init_df.to_frame(), new_df, how = 'left', left_on='country_of_origin_en', right_on='country_of_origin_en'+str(cf[4:]))
    except:
        init_df = pd.merge(init_df, new_df, how = 'left', left_on='country_of_origin_en', right_on='country_of_origin_en'+str(cf[4:]))
        
print("Done")

Month is April.csv
Month is August.csv
Month is December.csv
Month is February.csv
Month is January.csv
Month is July.csv
Month is June.csv
Month is March.csv
Month is May.csv
Month is November.csv
Month is October.csv
Month is September.csv
Done

# View the dataframe

In [10]:
init_df.head()

,country_of_origin_en,country_of_origin_enApril.csv,monthApril.csv,month_enApril.csv,valueApril.csv,country_of_origin_enAugust.csv,monthAugust.csv,month_enAugust.csv,valueAugust.csv,country_of_origin_enDecember.csv,...,month_enNovember.csv,valueNovember.csv,country_of_origin_enOctober.csv,monthOctober.csv,month_enOctober.csv,valueOctober.csv,country_of_origin_enSeptember.csv,monthSeptember.csv,month_enSeptember.csv,valueSeptember.csv
0,Afghanistan,Afghanistan,4,April,385,Afghanistan,8.0,August,670.0,Afghanistan,...,November,660.0,Afghanistan,10.0,October,675.0,Afghanistan,9.0,September,640.0
1,Albania,Albania,4,April,185,Albania,8.0,August,250.0,Albania,...,November,230.0,Albania,10.0,October,225.0,Albania,9.0,September,240.0
2,Rep. of Moldova,Rep. of Moldova,4,April,5,NaN,NaN,NaN,NaN,Rep. of Moldova,...,NaN,NaN,Rep. of Moldova,10.0,October,5.0,Rep. of Moldova,9.0,September,5.0
3,Mali,Mali,4,April,5,Mali,8.0,August,5.0,Mali,...,NaN,NaN,Mali,10.0,October,5.0,NaN,NaN,NaN,NaN
4,Ethiopia,Ethiopia,4,April,15,Ethiopia,8.0,August,20.0,Ethiopia,...,November,10.0,Ethiopia,10.0,October,10.0,Ethiopia,9.0,September,35.0

# Import Mann-Kendall

In [12]:
import mk_test

# Calculate the Mann-Kendall value and add it to the dataframe

In [13]:
init_df['MK Val']= 'No Data'
for idx, row in enumerate(init_df.iterrows()):
    mk_trend_vals = []
    for val in val_list:
        #print(init_df.at[idx,'Country'])
        mk_trend_vals.append(init_df.at[idx,val])

    try:
        print(mk_trend_vals)
        print(mk_test.mk_test(mk_trend_vals)[0])
        init_df.at[idx,'MK Val']  = mk_test.mk_test(mk_trend_vals)[0]
    except:
        print('ERROR')

[1195.0, 600.0, 585.0, 385, 550.0, 500.0, 495.0, 670.0, 640.0, 675.0, 660.0, 540.0]
no trend
[105.0, 100.0, 120.0, 185, 240.0, 235.0, 215.0, 250.0, 240.0, 225.0, 230.0, 200.0]
no trend
[nan, nan, 5.0, 5, 5.0, 5.0, nan, nan, 5.0, 5.0, nan, 5.0]
ERROR
[5.0, 20.0, 10.0, 5, 5.0, 10.0, 5.0, 5.0, nan, 5.0, nan, 5.0]
ERROR
[20.0, 20.0, 40.0, 15, 30.0, 15.0, 5.0, 20.0, 35.0, 10.0, 10.0, 25.0]
no trend
[45.0, 30.0, 50.0, 20, 35.0, 30.0, 35.0, 45.0, 30.0, 20.0, 50.0, 25.0]
no trend
[80.0, 110.0, 115.0, 35, 75.0, 75.0, 45.0, 30.0, 35.0, 50.0, 45.0, 55.0]
no trend
[415.0, 125.0, 95.0, 40, 45.0, 65.0, 110.0, 75.0, 125.0, 90.0, 75.0, 50.0]
no trend
[55.0, 85.0, 120.0, 45, 75.0, 35.0, 55.0, 105.0, 85.0, 75.0, 60.0, 25.0]
no trend
[65.0, 70.0, 75.0, 55, 95.0, 95.0, 80.0, 90.0, 100.0, 95.0, 95.0, 75.0]
no trend
[5.0, 5.0, 10.0, 5, 5.0, 10.0, 5.0, 5.0, nan, 5.0, 5.0, 15.0]
ERROR
[nan, 10.0, 30.0, 10, 10.0, 25.0, 5.0, 10.0, 5.0, 5.0, 10.0, 15.0]
ERROR
[5.0, 10.0, 5.0, 5, nan, nan, nan, nan, nan, nan, nan, nan]
ERROR
[2285.0, 1805.0, 1280.0, 570, 725.0, 1015.0, 1045.0, 1400.0, 1775.0, 2010.0, 1455.0, 975.0]
no trend
[95.0, 95.0, 90.0, 75, 95.0, 105.0, 120.0, 155.0, 110.0, 110.0, 135.0, 75.0]
no trend
[5.0, 5.0, 10.0, 5, 20.0, 20.0, 10.0, 10.0, 40.0, 25.0, 10.0, 5.0]
no trend
[130.0, 135.0, 170.0, 80, 95.0, 140.0, 115.0, 80.0, 95.0, 100.0, 90.0, 70.0]
no trend
[5.0, 5.0, 20.0, 5, 5.0, 5.0, 5.0, 10.0, 5.0, 10.0, 5.0, 5.0]
no trend
[50.0, 45.0, 80.0, 65, 110.0, 90.0, 140.0, 270.0, 295.0, 340.0, 255.0, 80.0]
increasing
[10.0, 20.0, 15.0, 15, 25.0, 20.0, 15.0, 35.0, 35.0, 40.0, 30.0, 25.0]
increasing
[10.0, 15.0, 10.0, 5, 20.0, 15.0, 15.0, 10.0, 10.0, 5.0, 5.0, 5.0]
no trend
[610.0, 665.0, 790.0, 515, 690.0, 640.0, 765.0, 790.0, 805.0, 805.0, 665.0, 620.0]
no trend
[nan, nan, nan, 5, nan, 5.0, 5.0, 5.0, nan, 5.0, 5.0, nan]
ERROR
[10.0, 25.0, 65.0, 30, 40.0, 40.0, 20.0, 45.0, 40.0, 40.0, 55.0, 40.0]
no trend
[20.0, 20.0, 15.0, 10, 10.0, 10.0, nan, 5.0, nan, nan, 5.0, nan]
ERROR
[60.0, 205.0, 175.0, 55, 140.0, 205.0, 35.0, 30.0, 25.0, 35.0, 20.0, 100.0]
decreasing
[720.0, 960.0, 500.0, 235, 480.0, 370.0, 440.0, 520.0, 960.0, 1155.0, 920.0, 620.0]
no trend
[nan, 10.0, 20.0, 5, 5.0, 10.0, nan, 5.0, 5.0, nan, 5.0, 5.0]
ERROR
[20.0, 65.0, 50.0, 10, 30.0, 35.0, 10.0, 50.0, 15.0, 40.0, 35.0, 40.0]
no trend
[5.0, 5.0, 5.0, 10, 10.0, 5.0, 10.0, 5.0, 5.0, 10.0, 15.0, nan]
ERROR
[90.0, 55.0, 45.0, 5, 15.0, 15.0, 5.0, 15.0, 10.0, 20.0, 10.0, 25.0]
no trend
[nan, nan, 5.0, 20, 20.0, 15.0, 15.0, 15.0, 25.0, 25.0, 45.0, 10.0]
ERROR
[5.0, 5.0, 10.0, 5, 15.0, 15.0, 5.0, 15.0, 15.0, 40.0, 85.0, 20.0]
increasing
[50.0, 35.0, 70.0, 35, 130.0, 95.0, 95.0, 75.0, 40.0, 45.0, 20.0, 15.0]
no trend
[5.0, 20.0, 5.0, 5, 5.0, 5.0, 5.0, 10.0, 5.0, 15.0, 5.0, nan]
ERROR

C:\Users\greg6750\Documents\IPython Notebooks\Advanced_Python_for_GIS_and_RS\Project 2\mk_test.py:40: RuntimeWarning: invalid value encountered in sign
  s += np.sign(x[j] - x[k])

# Filter out No Data values

In [14]:
trend_df = init_df[init_df['MK Val']!= 'No Data']

# Reset index to prepare to publish the result

In [15]:
trend_df.reset_index()

,index,country_of_origin_en,country_of_origin_enApril.csv,monthApril.csv,month_enApril.csv,valueApril.csv,country_of_origin_enAugust.csv,monthAugust.csv,month_enAugust.csv,valueAugust.csv,...,valueNovember.csv,country_of_origin_enOctober.csv,monthOctober.csv,month_enOctober.csv,valueOctober.csv,country_of_origin_enSeptember.csv,monthSeptember.csv,month_enSeptember.csv,valueSeptember.csv,MK Val
0,0,Afghanistan,Afghanistan,4,April,385,Afghanistan,8.0,August,670.0,...,660.0,Afghanistan,10.0,October,675.0,Afghanistan,9.0,September,640.0,no trend
1,1,Albania,Albania,4,April,185,Albania,8.0,August,250.0,...,230.0,Albania,10.0,October,225.0,Albania,9.0,September,240.0,no trend
2,4,Ethiopia,Ethiopia,4,April,15,Ethiopia,8.0,August,20.0,...,10.0,Ethiopia,10.0,October,10.0,Ethiopia,9.0,September,35.0,no trend
3,5,Morocco,Morocco,4,April,20,Morocco,8.0,August,45.0,...,50.0,Morocco,10.0,October,20.0,Morocco,9.0,September,30.0,no trend
4,6,Algeria,Algeria,4,April,35,Algeria,8.0,August,30.0,...,45.0,Algeria,10.0,October,50.0,Algeria,9.0,September,35.0,no trend
5,7,Palestinian,Palestinian,4,April,40,Palestinian,8.0,August,75.0,...,75.0,Palestinian,10.0,October,90.0,Palestinian,9.0,September,125.0,no trend
6,8,Egypt,Egypt,4,April,45,Egypt,8.0,August,105.0,...,60.0,Egypt,10.0,October,75.0,Egypt,9.0,September,85.0,no trend
7,9,Georgia,Georgia,4,April,55,Georgia,8.0,August,90.0,...,95.0,Georgia,10.0,October,95.0,Georgia,9.0,September,100.0,no trend
8,13,Syrian Arab Rep.,Syrian Arab Rep.,4,April,570,Syrian Arab Rep.,8.0,August,1400.0,...,1455.0,Syrian Arab Rep.,10.0,October,2010.0,Syrian Arab Rep.,9.0,September,1775.0,no trend
9,14,Bangladesh,Bangladesh,4,April,75,Bangladesh,8.0,August,155.0,...,135.0,Bangladesh,10.0,October,110.0,Bangladesh,9.0,September,110.0,no trend
10,15,India,India,4,April,5,India,8.0,August,10.0,...,10.0,India,10.0,October,25.0,India,9.0,September,40.0,no trend
11,16,Iran (Islamic Rep. of),Iran (Islamic Rep. of),4,April,80,Iran (Islamic Rep. of),8.0,August,80.0,...,90.0,Iran (Islamic Rep. of),10.0,October,100.0,Iran (Islamic Rep. of),9.0,September,95.0,no trend
12,17,Tunisia,Tunisia,4,April,5,Tunisia,8.0,August,10.0,...,5.0,Tunisia,10.0,October,10.0,Tunisia,9.0,September,5.0,no trend
13,18,Turkey,Turkey,4,April,65,Turkey,8.0,August,270.0,...,255.0,Turkey,10.0,October,340.0,Turkey,9.0,September,295.0,increasing
14,19,China,China,4,April,15,China,8.0,August,35.0,...,30.0,China,10.0,October,40.0,China,9.0,September,35.0,increasing
15,20,Nigeria,Nigeria,4,April,5,Nigeria,8.0,August,10.0,...,5.0,Nigeria,10.0,October,5.0,Nigeria,9.0,September,10.0,no trend
16,21,Pakistan,Pakistan,4,April,515,Pakistan,8.0,August,790.0,...,665.0,Pakistan,10.0,October,805.0,Pakistan,9.0,September,805.0,no trend
17,23,Cameroon,Cameroon,4,April,30,Cameroon,8.0,August,45.0,...,55.0,Cameroon,10.0,October,40.0,Cameroon,9.0,September,40.0,no trend
18,25,Dem. Rep. of the Congo,Dem. Rep. of the Congo,4,April,55,Dem. Rep. of the Congo,8.0,August,30.0,...,20.0,Dem. Rep. of the Congo,10.0,October,35.0,Dem. Rep. of the Congo,9.0,September,25.0,decreasing
19,26,Iraq,Iraq,4,April,235,Iraq,8.0,August,520.0,...,920.0,Iraq,10.0,October,1155.0,Iraq,9.0,September,960.0,no trend
20,28,Kuwait,Kuwait,4,April,10,Kuwait,8.0,August,50.0,...,35.0,Kuwait,10.0,October,40.0,Kuwait,9.0,September,15.0,no trend
21,30,Eritrea,Eritrea,4,April,5,Eritrea,8.0,August,15.0,...,10.0,Eritrea,10.0,October,20.0,Eritrea,9.0,September,10.0,no trend
22,32,Somalia,Somalia,4,April,5,Somalia,8.0,August,15.0,...,85.0,Somalia,10.0,October,40.0,Somalia,9.0,September,15.0,increasing
23,33,Stateless,Stateless,4,April,35,Stateless,8.0,August,75.0,...,20.0,Stateless,10.0,October,45.0,Stateless,9.0,September,40.0,no trend

# Save as CSV and publish as Feature Layer in ArcGIS Online

In [17]:
trend_csv = 'unhcr_trend_csv.csv'
trend_df.to_csv(trend_csv)
print('Publishing ' + trend_csv)

trend_csv_content = gis.content.add({}, trend_csv)
trend_layers = trend_csv_content.publish(None, {"Address":"country_of_origin_en"})
print('Done.')

Publishing unhcr_trend_csv.csv
Done.